enum LoaderActions {
  FETCH_PROJECTS = 'FETCH_PROJECTS',
  DELETE_PROJECT = 'DELETE_PROJECT',
  CREATE_PROJECT = 'CREATE_PROJECT',
  LOG_IN = 'LOG_IN',
  SIGN_IN = 'SIGN_IN',

  GAME_REQUEST = 'GAME_REQUEST ',
}

export default LoaderActions;
